name: Build

on:
  pull_request:
  push:
    paths:
      - 'scripts/**'
      - 'bin/**'
      - 'Dockerfile'
    branches:    
        - '*'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-18.04
    env:
      centos_repo_main: dodopizza/centos
      centos_repo_dev:  dodopizza/centos-dev
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to hub.docker
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image and check preinstalled app versions
        run: |
          docker build --rm --tag centos_local .
          docker run --rm centos_local bash -c '/version-info.sh'

      - name: Push to dodopizza/centos:latest
        if: github.ref == 'refs/heads/latest'
        run: |
          docker tag  centos_local ${centos_repo_main}:latest
          docker tag  centos_local ${centos_repo_dev}:latest
          docker push ${centos_repo_main}:latest
          docker push ${centos_repo_dev}:latest

      - name: Push to dodopizza/centos-dev:branch_name
        if: github.ref != 'refs/heads/latest'
        run: |
          branch_name=$( echo ${{ github.ref }} | sed -n 's/refs\/tags\/\(.*\)/\1/p' )
          docker tag  centos_local ${centos_repo_dev}:${branch_name}
          docker push ${centos_repo_dev}:${branch_name}
