name: Build

on:
  pull_request:
  push:
    branches:
        - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04
    env:
      centos_repo_main: dodopizza/centos
      centos_repo_dev:  dodopizza/centos-dev
      centos_repo_ghcr_main: ghcr.io/dodopizza/centos
      centos_repo_ghcr_dev:  ghcr.io/dodopizza/centos-dev
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and check preinstalled app versions
        run: |
          docker build --rm --tag centos_local .
          docker run --rm centos_local bash -c '/version-info.sh'

      - name: Push to dodopizza/centos-dev:<branch_short_sha>
        run: |
          branch_short_sha=$( echo ${{ github.ref }} | sha1sum | cut -c1-6 )
          docker tag  centos_local ${centos_repo_dev}:${branch_short_sha}
          docker tag  centos_local ${centos_repo_ghcr_dev}:${branch_short_sha}
          docker push ${centos_repo_dev}:${branch_short_sha}
          docker push ${centos_repo_ghcr_dev}:${branch_short_sha}

          echo
          echo "Dev image tag: ${centos_repo_dev}:${branch_short_sha}"
          echo "Dev image tag: ${centos_repo_ghcr_dev}:${branch_short_sha}"
          echo

      - name: Push to dodopizza/centos:latest and dodopizza/centos-dev:latest
        if: github.ref == 'refs/heads/latest'
        run: |
          docker tag  centos_local ${centos_repo_main}:latest
          docker tag  centos_local ${centos_repo_dev}:latest
          docker tag  centos_local ${centos_repo_ghcr_main}:latest
          docker tag  centos_local ${centos_repo_ghcr_dev}:latest
          docker push ${centos_repo_main}:latest
          docker push ${centos_repo_dev}:latest
          docker push ${centos_repo_ghcr_main}:latest
          docker push ${centos_repo_ghcr_dev}:latest
